version: "3"

services:

  back:
    container_name: github-api-back
    image: vitormsp/github-api-back
    ports:
      - "3001:3001"

  front:
    container_name: github-api-front
    image: vitormsp/github-api-front
    ports:
      - "80:80"
    depends_on:
      - back